-- MySQL Script generated by MySQL Workbench
-- sex 08 ago 2025 10:25:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lanchonete
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lanchonete
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lanchonete` DEFAULT CHARACTER SET utf8 ;
USE `lanchonete` ;

-- -----------------------------------------------------
-- Table `lanchonete`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lanchonete`.`tb_categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lanchonete`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lanchonete`.`tb_produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `data_validade` DATE NOT NULL,
  `quantidade` INT NOT NULL,
  `foto` VARCHAR(200) NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_tb_produto_tb_categoria1_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `lanchonete`.`tb_categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lanchonete`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lanchonete`.`tb_cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lanchonete`.`tb_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lanchonete`.`tb_funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `cargo` VARCHAR(60) NOT NULL,
  `telefone` VARCHAR(12) NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lanchonete`.`tb_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lanchonete`.`tb_venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `id_produto` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_funcionario` INT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `data_venda` DATE NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_tb_venda_tb_produto_idx` (`id_produto` ASC) VISIBLE,
  INDEX `fk_tb_venda_tb_cliente1_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_tb_venda_tb_funcionario1_idx` (`id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_venda_tb_produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `lanchonete`.`tb_produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_venda_tb_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `lanchonete`.`tb_cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_venda_tb_funcionario1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `lanchonete`.`tb_funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `lanchonete`.`tb_produto` (`nome`, `data_validade`, `quantidade`) VALUES
('Fita', '2025-04-16', 34),
('Lápis', '2025-05-24', 51),
('Cadeira', '2025-04-28', 99),
('Caneta', '2025-07-13', 27),
('Caderno', '2025-03-22', 75),
('Bolacha', '2025-08-12', 49),
('Sorvete', '2025-06-02', 14),
('Feijão', '2025-05-18', 88),
('Biscoito', '2025-05-01', 60),
('Arroz', '2025-11-09', 35),
('Refrigerante', '2025-07-27', 22),
('Macarrão', '2025-10-14', 92),
('Achocolatado', '2025-02-20', 45),
('Café', '2025-12-05', 66),
('Óleo', '2025-01-25', 53),
('Maçã', '2025-04-05', 31),
('Tomate', '2025-03-30', 79),
('Alface', '2025-04-25', 42),
('Cebola', '2025-07-22', 25),
('Alho', '2025-06-18', 60),
('Pão', '2025-04-10', 18),
('Manteiga', '2025-08-04', 67),
('Iogurte', '2025-06-28', 89),
('Leite', '2025-11-17', 90),
('Carne', '2025-03-14', 62),
('Frango', '2025-09-06', 71),
('Peixe', '2025-05-03', 38),
('Queijo', '2025-02-10', 11),
('Linguiça', '2025-10-30', 50),
('Salsicha', '2025-01-19', 29),
('Verduras', '2025-06-23', 40),
('Cenoura', '2025-07-01', 57),
('Beterraba', '2025-09-15', 56),
('Pera', '2025-10-02', 30),
('Manga', '2025-08-19', 72),
('Abacaxi', '2025-12-11', 63),
('Coco', '2025-05-12', 43),
('Banana', '2025-04-09', 65),
('Morango', '2025-03-25', 59),
('Kiwi', '2025-07-16', 48),
('Uva', '2025-06-01', 82),
('Cabelos', '2025-05-22', 69),
('Xampu', '2025-01-14', 55),
('Condicionador', '2025-02-07', 64),
('Creme', '2025-11-21', 84),
('Sabonete', '2025-03-08', 70),
('Desodorante', '2025-09-20', 39),
('Toalha', '2025-07-05', 76),
('Escova', '2025-10-24', 83),
('Pasta de dente', '2025-02-27', 26),
('Fio dental', '2025-06-06', 50),
('Protetor solar', '2025-08-15', 36),
('Luva', '2025-04-01', 58),
('Papel higiênico', '2025-12-04', 44),
('Fralda', '2025-11-03', 37),
('Lenço', '2025-05-06', 73),
('Papel toalha', '2025-09-13', 78),
('Álcool em gel', '2025-03-03', 80),
('Desinfetante', '2025-01-30', 61),
('Detergente', '2025-04-12', 68),
('Esponja', '2025-07-09', 41),
('Cera', '2025-10-08', 47),
('Saco de lixo', '2025-06-13', 52),
('Vassoura', '2025-05-30', 32),
('Rodo', '2025-02-14', 74),
('Pá', '2025-03-01', 81),
('Aspirador', '2025-11-01', 23),
('Escada', '2025-09-29', 21),
('Tábua de passar', '2025-08-26', 19),
('Ferro', '2025-10-11', 18),
('Cesto de roupa', '2025-07-17', 17),
('Panela', '2025-01-05', 94),
('Frigideira', '2025-12-15', 10),
('Microondas', '2025-04-23', 85),
('Geladeira', '2025-02-01', 93),
('Fogão', '2025-05-15', 98),
('Cafeteira', '2025-09-08', 24),
('Liquidificador', '2025-07-25', 27),
('Batedeira', '2025-10-04', 22),
('Processador', '2025-08-22', 28),
('Requeijão', '2025-05-19', 74),
('Creme de leite', '2025-06-14', 82),
('Azeite', '2025-09-02', 45),
('Vinagre', '2025-12-07', 34),
('Sal', '2025-03-10', 53),
('Pimenta', '2025-10-16', 62),
('Alho em pó', '2025-11-28', 65),
('Tempero', '2025-08-05', 77),
('Molho', '2025-07-12', 79),
('Mostarda', '2025-06-17', 46),
('Ketchup', '2025-04-18', 40),
('Maionese', '2025-01-08', 36),
('Chá', '2025-05-08', 30),
('Café solúvel', '2025-11-25', 90),
('Bebida isotônica', '2025-10-23', 33),
('Água', '2025-09-11', 89),
('Suco', '2025-02-18', 56),
('Bebida energética', '2025-07-03', 50),
('Água com gás', '2025-08-30', 69),
('Água saborizada', '2025-04-14', 91),
('Cerveja', '2025-01-12', 66),
('Vinho', '2025-06-09', 73),
('Whisky', '2025-05-21', 72),
('Champagne', '2025-03-27', 76),
('Tequila', '2025-12-01', 74),
('Rum', '2025-10-27', 29),
('Cachaça', '2025-08-17', 37),
('Vodka', '2025-09-21', 49),
('Gin', '2025-07-28', 56),
('Laranja', '2025-06-25', 44);
