-- MySQL Script generated by MySQL Workbench
-- ter 20 mai 2025 10:28:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lanchonete
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lanchonete
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lanchonete` DEFAULT CHARACTER SET utf8 ;
USE `lanchonete` ;

-- -----------------------------------------------------
-- Table `lanchonete`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lanchonete`.`tb_produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `data_validade` DATE NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lanchonete`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lanchonete`.`tb_cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lanchonete`.`tb_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lanchonete`.`tb_funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `cargo` VARCHAR(60) NOT NULL,
  `telefone` VARCHAR(12) NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
