-- MySQL Script generated by MySQL Workbench
-- ter 07 out 2025 07:43:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lanchonete
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lanchonete
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lanchonete` DEFAULT CHARACTER SET utf8 ;
USE `lanchonete` ;

-- -----------------------------------------------------
-- Table `lanchonete`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lanchonete`.`tb_categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lanchonete`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lanchonete`.`tb_produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `data_validade` DATE NOT NULL,
  `quantidade` INT NOT NULL,
  `foto` VARCHAR(200) NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_tb_produto_tb_categoria1_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `lanchonete`.`tb_categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lanchonete`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lanchonete`.`tb_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `tipo` CHAR(1) NOT NULL DEFAULT 'c',
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `tb_usuariocol_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lanchonete`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lanchonete`.`tb_cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_tb_cliente_tb_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_cliente_tb_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `lanchonete`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lanchonete`.`tb_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lanchonete`.`tb_funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `cargo` VARCHAR(60) NOT NULL,
  `telefone` VARCHAR(12) NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  INDEX `fk_tb_funcionario_tb_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_funcionario_tb_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `lanchonete`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lanchonete`.`tb_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lanchonete`.`tb_venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `id_produto` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_funcionario` INT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `data_venda` DATE NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_tb_venda_tb_produto_idx` (`id_produto` ASC) VISIBLE,
  INDEX `fk_tb_venda_tb_cliente1_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_tb_venda_tb_funcionario1_idx` (`id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_venda_tb_produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `lanchonete`.`tb_produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_venda_tb_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `lanchonete`.`tb_cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_venda_tb_funcionario1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `lanchonete`.`tb_funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
